/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package billingwarnet;

import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.util.HashSet;
import java.util.Set;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.ScrollPaneLayout;

/**
 *
 * @author zak
 */
public class BillingAdminMenu extends javax.swing.JPanel {

    /**
     * Creates new form BillingAdminMenu
     */
    public BillingAdminMenu() {
        initComponents();
        
    }

    public void setPanelGroup()
    {
        //System.out.println("aaaaa");
        BillingClientStatus Com1 = new BillingClientStatus();
        BillingClientStatus Com2 = new BillingClientStatus();
        BillingClientStatus Com3 = new BillingClientStatus();
        BillingClientStatus Com4 = new BillingClientStatus();
        BillingClientStatus Com5 = new BillingClientStatus();
        BillingClientStatus Com6 = new BillingClientStatus();
        BillingClientStatus Com7 = new BillingClientStatus();
        BillingClientStatus Com8 = new BillingClientStatus();
        
        
      innerPanel.setLayout( new GridLayout(0,3));
        
        innerPanel.add(Com1);
        Com1.setLocation(150, 150);
        innerPanel.add(Com2);
        Com2.setLocation(300, 150);
        innerPanel.add(Com3);
        Com3.setLocation(450, 150);
        innerPanel.add(Com4);
        Com4.setLocation(150, 300);
        innerPanel.add(Com5);
        Com5.setLocation(300, 300);
        innerPanel.add(Com6);
        Com6.setLocation(450, 300);
        innerPanel.add(Com7);
        Com7.setLocation(150, 450);
        innerPanel.add(Com8);
        Com8.setLocation(300, 450);
        
        Com1.setVisible(true);
        Com2.setVisible(true);
        Com3.setVisible(true);
        Com4.setVisible(true);
        Com5.setVisible(true);
        Com6.setVisible(true);
        Com7.setVisible(true);
        Com8.setVisible(true);
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        scrollPanel = new javax.swing.JScrollPane();
        innerPanel = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(600, 480));

        jLabel1.setText("Active Clients");

        javax.swing.GroupLayout innerPanelLayout = new javax.swing.GroupLayout(innerPanel);
        innerPanel.setLayout(innerPanelLayout);
        innerPanelLayout.setHorizontalGroup(
            innerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );
        innerPanelLayout.setVerticalGroup(
            innerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );

        scrollPanel.setViewportView(innerPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 445, Short.MAX_VALUE)
                .addGap(48, 48, 48))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPanel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel innerPanel;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JScrollPane scrollPanel;
    // End of variables declaration//GEN-END:variables
}
