/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package billingwarnet;

/**
 *
 * @author zak
 */
public class BillingLogin extends javax.swing.JPanel {


    DataClient dataClient;
    DataMember dataMember;
    Admin dataAdmin;
    boolean isAdmin;
    boolean isValid;
    String admin;
    String password;
    /**
     * Creates new form BillingLogin
     */
    public BillingLogin() {
        initComponents();
        admin = "admin";
        password = "admin";
        isAdmin=false;
    }

    
    public void LoginData(DataClient dataClient,Admin dataAdmin, DataMember dataMember)
    {
        this.dataClient = dataClient;
        this.dataAdmin = dataAdmin;
        this.dataMember = dataMember;
        isAdmin = this.dataAdmin.getAdmin();
        
        checkUser(isAdmin);
    }
    
    private void checkUser(boolean isAdmin)
    {
        if(isAdmin)
        {
            userStatus.setText("Admin Login");
        }
        else userStatus.setText("Member Login");
    }
    
    public boolean validate(String admin, String password)
    {
        if(isAdmin)
        {
        isValid = this.password.equals(password) && this.admin.equals(admin) ? true : false;
        return isValid;
        }
        else
        {
        isValid = this.password.equals(password) && this.admin.equals(admin) ? true : false;
        return isValid;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginUsername = new javax.swing.JLabel();
        loginPassword = new javax.swing.JLabel();
        inputUsername = new javax.swing.JTextField();
        inputPassword = new javax.swing.JTextField();
        sendLogin = new javax.swing.JButton();
        userStatus = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(500, 400));

        loginUsername.setText("Username");

        loginPassword.setText("Password");

        inputUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputUsernameActionPerformed(evt);
            }
        });

        sendLogin.setText("Ok");
        sendLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendLoginActionPerformed(evt);
            }
        });

        userStatus.setText("UserStatus");
        checkUser(isAdmin);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loginUsername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loginPassword)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sendLogin)
                            .addComponent(inputPassword))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(userStatus)
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userStatus)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginUsername)
                    .addComponent(inputUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginPassword)
                    .addComponent(inputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(sendLogin)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void inputUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputUsernameActionPerformed

    private void sendLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendLoginActionPerformed

        if(validate(inputUsername.getText(), inputPassword.getText()))
        {
            if(isAdmin)
            {
                MainFrame.frame.add(MainFrame.adminMenu);
                MainFrame.login.setVisible(false);
            }
            else
            {
                MainFrame.transaction.setDataClient(dataClient);
                MainFrame.transaction.setDataMember(dataMember);
                MainFrame.transaction.setUserName();
                MainFrame.frame.add(MainFrame.transaction);
                MainFrame.login.setVisible(false);
            }
        }
        else
            MainFrame.infoBox("Username / Passoword Salah", "Peringatan");
    }//GEN-LAST:event_sendLoginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JTextField inputPassword;
    protected javax.swing.JTextField inputUsername;
    private javax.swing.JLabel loginPassword;
    private javax.swing.JLabel loginUsername;
    protected javax.swing.JButton sendLogin;
    protected javax.swing.JLabel userStatus;
    // End of variables declaration//GEN-END:variables
}