/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package billingwarnet;

import java.awt.Component;
import javax.swing.JPanel;

/**
 *
 * @author zak
 */
public class BillingMainMenu extends JPanel {

    /**
     * Creates new form BillingMainMenu
     */
    DataClient dataClient;
    
    public BillingMainMenu() {
        initComponents();
    }

    public void setDataClient(DataClient dataClient)
    {
        this.dataClient = dataClient;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminBtn = new javax.swing.JButton();
        memberBtn = new javax.swing.JButton();
        guestBtn = new javax.swing.JButton();

        adminBtn.setText("Admin");
        adminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminBtnActionPerformed(evt);
            }
        });

        memberBtn.setText("Member");
        memberBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberBtnActionPerformed(evt);
            }
        });

        guestBtn.setText("Guest");
        guestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guestBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(adminBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(memberBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(guestBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(adminBtn)
                .addGap(18, 18, 18)
                .addComponent(memberBtn)
                .addGap(18, 18, 18)
                .addComponent(guestBtn)
                .addContainerGap(105, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void memberBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberBtnActionPerformed
        MainFrame.admin.setAdmin(false);
        MainFrame.login.LoginData(MainFrame.getDataClient(),MainFrame.getAdmin(),MainFrame.getDataMember());
        MainFrame.frame.add(MainFrame.login);
        MainFrame.mainMenu.setVisible(false);
        
    }//GEN-LAST:event_memberBtnActionPerformed

    private void guestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guestBtnActionPerformed
        MainFrame.frame.add(MainFrame.transaction);
        MainFrame.transaction.setDataClient(dataClient);
        MainFrame.mainMenu.setVisible(false);
    }//GEN-LAST:event_guestBtnActionPerformed

    private void adminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminBtnActionPerformed
        MainFrame.admin.setAdmin(true);
        MainFrame.login.LoginData(MainFrame.getDataClient(),MainFrame.getAdmin(),MainFrame.getDataMember());
        MainFrame.frame.add(MainFrame.login);
        MainFrame.mainMenu.setVisible(false);
        System.out.println(MainFrame.admin.getAdmin());
    }//GEN-LAST:event_adminBtnActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton adminBtn;
    protected javax.swing.JButton guestBtn;
    protected javax.swing.JButton memberBtn;
    // End of variables declaration//GEN-END:variables
}
